### ISSUE TITLE
Deprecate use of lead_time in PullRequest Model

### ISSUE THREAD

**Issue by amoghjalan** [middlewarehq/middleware#117]
**Why is this required?**

The lead time attribute in the PullRequests model is no longer cached and should be deprecated. This change was made to align with the new calculation method for merge to deploy, which now depends on the deployment type for TeamRepos being either `PR_MERGE` or `WORKFLOW`.

### Scope:

1. **Remove `lead_time` attribute usage from frontend system for pull requests.**
   
   The frontend system should no longer rely on the `lead_time` attribute when displaying pull request data.

2. **Remove `lead_time` attribute usage from core backend APIs that return Pull requests data.**
   
   Update core backend APIs to no longer return the `lead_time` attribute when fetching pull request data.

3. **Drop lead_time column from the database.**
   
   Remove the `lead_time` column from the database schema as it is no longer required.

**Comment by Kamlesh72** [comment]
@amoghjalan Is this fixed by #243 ?

**Comment by amoghjalan** [comment]
Yeah @Kamlesh72 , thank for reminding!
