### ISSUE TITLE
Remove team repos updation logic from repo and move it to service layer

### ISSUE THREAD

**Issue by amoghjalan** [middlewarehq/middleware#148]
## Why do we need this ?
Currently a lot of logic for team repos is written in Repo Layer.
The logic should remain in service layer.

Refer #147 for changes required

## Acceptance Criteria

- [ ] Move Logical Code to it's own service layer

## Further Comments / References  
#147

**Comment by Kamlesh72** [comment]
Hey @amoghjalan can you verify if this is correct?
Move functions like get_existing_team_repos, get_team_repos_by_repo_id_for_team +7 more To new file store/repos/teams.py with class TeamRepoService ?

**Comment by amoghjalan** [comment]
Hey @Kamlesh72 I believe the issue has been resolved 
the `update_team_repos` methods has been already refactored as opposed to what it is in the PR link in issue discription
https://github.com/middlewarehq/middleware/blob/ffc623d98f29c66697582046e3fd545047e585cf/backend/analytics_server/mhq/store/repos/code.py#L60

Yeah, this was resolved in #449.
Thanks for verifying!
