### ISSUE TITLE
Refactor Team Repos and Team Incidents Logic in Incident Service

### ISSUE THREAD

**Issue by amoghjalan** [middlewarehq/middleware#150]
## Why do we need this ?
The Team Repos and Team Incidents Logic should have not been added to Incident Service, Refactor it to it's own service

## Acceptance Criteria

- [ ] Team Incidents Service is updated while updating Team Repos, the code needs refactoring.

**Comment by Kamlesh72** [comment]
@amoghjalan I want to work on this issue.
I didn't find any TeamRepos related code in IncidentsRepoService.
It has OrgIncidentService, IncidentsBookmark, TeamIncidentService. 
So do you mean to separate TeamIncidentService logic from IncidentsRepoService?

**Comment by xyfer17** [comment]
@amoghjalan could you please assign these issue to me, i would like to take this up.

**Comment by jayantbh** [comment]
Hey @xyfer17, I've assigned this to you.

**Comment by xyfer17** [comment]
@amoghjalan @jayantbh would i have to create separate file base for team repos and team incidents service to refactor the code.
Could you explain a bit more about on this ?

**Comment by jayantbh** [comment]
Hey @xyfer17, @amoghjalan isn't part of the team at the moment, but @adnanhashmi09 or @samad-yar-khan should be able to help you out.

**Comment by xyfer17** [comment]
> @amoghjalan @jayantbh would i have to create separate file base for team repos and team incidents service to refactor the code. Could you explain a bit more about on this ?

@adnanhashmi09 @samad-yar-khan could please help me in the above ?
