### ISSUE TITLE
Drop id from TeamIncidentService table

### ISSUE THREAD

**Issue by amoghjalan** [middlewarehq/middleware#151]
## Why do we need this ?
id column that is primary key in TeamIncidentService is not required, we can drop it and use (team_id, service_id) as primary key.

## Acceptance Criteria

- [ ] DROP id column from TeamIncidentService, make (team_id, service_id) as primary key
- [ ] Check usages of TeamIncidentService.id in codebase and remove them

**Comment by guntarakesh** [comment]
@amoghjalan i can work on this issue but can you please guide me towards solution

**Comment by Kamlesh72** [comment]
I think this is completed by #212 #213 #219

**Comment by jayantbh** [comment]
Hey @guntarakesh and @Kamlesh72, yeah that might be right. We'll get this checked and let you know.

**Comment by amoghjalan** [comment]
Thanks @Kamlesh72
