### ISSUE TITLE
Deprecate TeamRepos.prod_branch 

### ISSUE THREAD

**Issue by amoghjalan** [middlewarehq/middleware#152]
## Why do we need this ?
TeamRepos.prod_branch is no longer used in analytics, rather TeamRepos.prod_branches is used.

## Acceptance Criteria

- [ ] Find it's usages and deprecate them
- [ ] Drop it from DB migration script

**Comment by Kamlesh72** [comment]
@amoghjalan Can be closed by #212
Also pls do check this, https://github.com/middlewarehq/middleware/blob/182eac655751c995459558e28cf15e0de1fe6154/web-server/src/constants/db.ts#L147

**Comment by jayantbh** [comment]
@adnanhashmi09 @samad-yar-khan might be better suited to confirm.
