### ISSUE TITLE
Can we please mention the version numbers for all pre-requisites to run this project?

### ISSUE THREAD

**Issue by dhruvagarwal** [middlewarehq/middleware#168]
### Description:
I was unable to run `dev.sh` as requested because of a package version mismatch.
<img width="896" alt="Screenshot 2024-04-24 at 3 37 06 PM" src="https://github.com/middlewarehq/middleware/assets/4587641/510f758a-2582-4115-a182-7cacf72921de">

Can we please mention the pre-req versions for each project dependency?

**Comment by ad1tyayadav** [comment]
@jayantbh Hello, 
I'm created a pull request for this issue please check this - https://github.com/middlewarehq/middleware/pull/570
and also this is my first PR.

**Comment by sahitya-chandra** [comment]
@jayantbh @dhruvagarwal Sir, Can you give some more detail on what should be the appropriate solution for this issue. I want to give it a try.

**Comment by jayantbh** [comment]
I think a simple check that runs at the start of the script to check that all versions are correct will do, and if something is off, it specifies which version of what thing is mismatching.

I think there was something implemented for that as well, you could check if that's indeed the case first. @sahitya-chandra

**Comment by sahitya-chandra** [comment]
Sir, can you tell me what was implemented

**Comment by jayantbh** [comment]
That's where the "exploring the codebase" part comes in. :)
I expect you'll find something in `dev.sh` or the `cli` submodule.

**Comment by sahitya-chandra** [comment]
@jayantbh sir, i am thinking of a solution like when user runs the cmd ./dev.sh we ask him about the required node version is installed in his pc or not. If the reply is yes then we can proceed otherwise we can tell him to install the required version
