### ISSUE TITLE
Infinitely growing list of logs from API server in dev mode

### ISSUE THREAD

**Issue by jayantbh** [middlewarehq/middleware#183]
### Description:

Running ./dev.sh shows that apiserver is loading a seeminly infinite amount of logs that causes the container storage to fill up and crash other things

### Steps to reproduce:

1. Run ./dev.sh
2. Wait for dockerfile setup steps to run though
3. Eventually see logs from api, web, and other sources to start streaming in
4. Notice that api logs keep coming in rapidly, and of course since this is being written to the disk, it takes up all the space

### Expected behavior:

It should not create so many logs as to fill up the disk.

**Comment by amoghjalan** [comment]
We have decided to keep interactive CLI on hold as part of developer mode. While someone picks it up, the dev.sh script has been updated to use docker compose watch directly instead.
I shall create a ticket for documentation to be updated with commands through which one can look into individual logs for now.
