### ISSUE TITLE
Github action job for building ARM images takes a very long time and fails

### ISSUE THREAD

**Issue by adnanhashmi09** [middlewarehq/middleware#200]
### Description:

The ARM build for docker images is taking an excessively long time (around 1 hour) and failing, while the AMD build is successful and takes only 5 minutes.

### Steps to reproduce:

1. Trigger the workflow to build the Docker images.
2. Observe the build process and timings for both ARM and AMD platforms.

### Expected behavior:

Both ARM and AMD builds should complete successfully within a reasonable time frame, without any significant difference in build times between the two platforms.

### Actual behavior:

The ARM build takes around 1 hour and fails, while the AMD build completes successfully in just 5 minutes.
![image](https://github.com/middlewarehq/middleware/assets/56730784/84424f86-3ae3-480e-99b9-9556dc7293af)

### Server Setup Information:

- Operating System: Ubuntu (GitHub Actions runner)
- Deployment Method: Docker

### Additional context

This issue seems to be related to the performance and compatibility of the ARM build process with the GitHub Actions runner environment. Additional investigation is needed to identify the root cause of the excessive build time and failure for the ARM platform. Potential factors to consider include:

- Compatibility of the ARM build environment with the specific dependencies or tools required for the project.
- Optimization of the build process for ARM architectures.
- Resource allocation and constraints within the GitHub Actions runner environment for ARM builds.

It would be beneficial to review the build logs and error messages for the failed ARM builds to gain more insights into the specific issues encountered.

**Comment by amoghjalan** [comment]
https://github.com/nodejs/docker-node/issues/1335
