### ISSUE TITLE
pytest and black workflows should not run for web-server changes

### ISSUE THREAD

**Issue by samad-yar-khan** [middlewarehq/middleware#224]
### Description:

The code base is divided into two portions, the web-server (typescript/next js) and apiserver (python/flask). pytests and black workflows should only run when changes are made to python directory or apiserver as they are focused towards that.

At the moment these workflows run for all PRs and may be an overhead for devs contributing strictly to web-server.

### Steps to reproduce:

1.  Make Changes to web-server
2. Check Workflow runs

Example: #223 

### Expected behavior:

- Python and flask centric workflows should run only when changes are made to apisever.

### Actual behavior:

- pytest and black run on all PRs

### Server Setup Information:

- Operating System: 
- Deployment Method:

**Comment by JuanJoseLL** [comment]
I would like to work in this issue, can I get assigned ?

**Comment by samad-yar-khan** [comment]
> I would like to work in this issue, can I get assigned ?

Hey @JuanJoseLL, sure, I will assign you the issue. Feel free to give this a try. You can discuss your approach or any queries you might have in this issue thread itself. Thanks 🚀
