### ISSUE TITLE
Separate Log streaming for API Analytics and Sync server

### ISSUE THREAD

**Issue by samad-yar-khan** [middlewarehq/middleware#265]
### Description:

We currently have a single log stream for server and analytic server.

### Steps to reproduce:

1. `./dev.sh`
2. Wait for container to start
3. Switch to api logs

### Expected behavior:

- Separate log streams for analytics sever

### Actual behavior:
- Single screen for sync and analytics

### Server Setup Information:

- Operating System: 
- Deployment Method:

**Comment by adnanhashmi09** [comment]
Closing this, as this was fixed in #368
