### ISSUE TITLE
UI breaking in onboarding

### ISSUE THREAD

**Issue by Git-DEmiGoD** [middlewarehq/middleware#271]
### Description:

just setup the project using ./dev.sh and the ui is breaking

### Steps to reproduce:

1. Take a fresh pull
2. ./dev.sh

### Expected behavior:

- Should load

### Actual behavior:

![image](https://github.com/middlewarehq/middleware/assets/71969865/64a7eda8-bd4b-4c0b-a78c-d162cc228797)

### Server Setup Information:

- Operating System: 
- Deployment Method:

**Comment by Git-DEmiGoD** [comment]
works after deleting and rebuilding image

**Comment by jayantbh** [comment]
It appears this was just a case of an outdated image. A fix for #342 should mitigate this.

**Comment by jayantbh** [comment]
Closing since there hasn't been any new activity on this. :)
