### ISSUE TITLE
Cant see any repos

### ISSUE THREAD

**Issue by Git-DEmiGoD** [middlewarehq/middleware#272]
### Description:

Added token but cant see any repos

### Steps to reproduce:

1. Add token
2. Create team
3. Add repos

### Expected behavior:

Load personal repos or give option for mocking data.

### Actual behavior:

no repos loaded to add to team
![image](https://github.com/middlewarehq/middleware/assets/71969865/46f8849a-ea51-450d-bf1d-37bf2fa3aa14)

### Server Setup Information:

- Operating System: 
- Deployment Method:

**Comment by Git-DEmiGoD** [comment]
![image](https://github.com/middlewarehq/middleware/assets/71969865/7eb709d9-d35b-48d8-aa87-dd47206bc4fe)

**Comment by jayantbh** [comment]
Hi @Git-DEmiGoD! Sorry for the super late reply. Could you update the image and container to the latest release and confirm if it's still the case?

**Comment by jayantbh** [comment]
Hey @Git-DEmiGoD, let us know if you're still having this issue. We'll close this soon if there's no further activity.
