### ISSUE TITLE
Notify the User if a new version of the product or new image is available

### ISSUE THREAD

**Issue by samad-yar-khan** [middlewarehq/middleware#342]
## Why do we need this ?

- There will be a number of changes made to the product, this may leave the user with an older docker image that they might be running, we need a message inside the product or in logs that can request the user to get the pull for the latest docker image and update their running version.

## Acceptance Criteria

- [ ] Message requesting user to take the pull of latest docker image when its available.

**Comment by jayantbh** [comment]
This was resolved.
