### ISSUE TITLE
Create Team repository search is missing repositories

### ISSUE THREAD

**Issue by ed-grow** [middlewarehq/middleware#354]
### Description:

When you try to create a team and select repositories for that team from the Add Repositories search box, not all of the repositories are selectable from the search box.  Searching for a repo by name yields "No repositories found".

In my case, my personal access token grants access to 3 organizations.  Through some brute force testing, it seems like the search function seems to only return repositories that are within the first ~31 repositories (sorted alphabetically) of the first organization (sorted alphabetically).  It does not return the other ~490 repositories in the first organization or **any** of the repositories in the other 2 organizations.

### Steps to reproduce:

1. Create an organization with ~50 repositories
2. Create a personal access token with access to that organization
3. Set up a GitHub integration using that personal access token
4. Go to the Create Team screen
5. Enter the name of the last (50th) repository (alphabetically) in the search box

### Expected behavior:

You see the name of the repository in the search dropdown and you can select the repository

### Actual behavior:

"No repositories found"

![Screenshot 2024-05-14 at 1 21 05 PM](https://github.com/middlewarehq/middleware/assets/120395431/0695dda0-5325-40a9-9879-ee21d2604a47)

### Server Setup Information:

- Operating System: MacOS Sonoma 14.4.1
- Deployment Method: Docker middlewareeng/middleware:0.1.2

**Comment by jayantbh** [comment]
Hey @ed-grow! Thanks for reporting this one. We'll sort this out ASAP. Within a day max. Let us know if you're willing to give it a shot!

**Comment by jayantbh** [comment]
Hey @ed-grow a mitigation has been deployed for this. You'd have to update the docker image to get the updated fixes.
Though the current fix is kind of a hotfix. A more comprehensive patch is coming soon.
Nonetheless, you should be unblocked at the moment. :)

**Comment by podlejskib** [comment]
So in my org we have more than 12k repositories. Currently, we can't try to use middleware. 
My suggestion could be - add manually links to repo in, for example "advanced view".

**Comment by jayantbh** [comment]
Hey @podlejskib, the fix coming in within the next couple of hours will enable you to search through any repos you have. :)
Could you mention what org you belong to? Our enterprise version would be really well suited to handle that kind of volume.
You could send us a ping at contact@middlewarehq.com if that seems like something you'd want to try. :)

**Comment by jayantbh** [comment]
Hey @podlejskib and @ed-grow. This should be properly sorted.
Please update your docker images and re-run the thing.
Let us know how it goes. :)
