### ISSUE TITLE
Add Gitlab platform integration

### ISSUE THREAD

**Issue by thelazyoxymoron** [middlewarehq/middleware#358]
Having Gitlab (along with Github) as a platform integration should cover majority of the software teams out there.

**Comment by jayantbh** [comment]
This is on our roadmap too! Love to see some demand for this.
Would you like to work with our team to get started on this? No pressure, we'd take care of this soon enough anyway. :)

**Comment by jayantbh** [comment]
Hey @thelazyoxymoron! We've just launched our Gitlab integration! 🎉 
Feel free to pull the latest version of `middleware` to try it out!

Instructions:
https://github.com/middlewarehq/middleware?tab=readme-ov-file#-quick-start

You may need to uninstall/remove any past versions and volume of Middleware. You'll find instructions for that in the troubleshooting section:
https://github.com/middlewarehq/middleware?tab=readme-ov-file#-quick-start:~:text=Then%20run%20following%20command%20before%20running%20the%20container

With that, we'll now finally close the issue. :)
