### ISSUE TITLE
Remove User not added tooltip

### ISSUE THREAD

**Issue by dhruvagarwal** [middlewarehq/middleware#366]
### Description:
On hovering over author in PR details, we get this tool tip saying User not added to MHQ. 
<img width="1007" alt="Screenshot 2024-05-18 at 8 00 37 AM" src="https://github.com/middlewarehq/middleware/assets/4587641/da6590c1-6ec0-4903-839e-ba7010169657">

### Steps to reproduce:

1. Go to http://localhost:3333/dora-metrics
2. Click on See Details on Lead Time
<img width="684" alt="Screenshot 2024-05-18 at 8 03 41 AM" src="https://github.com/middlewarehq/middleware/assets/4587641/f8cb3719-c8c0-432a-a7f0-5ec2aa5388f1">
3. In the list that opens up, hover on the author

### Expected behavior:

Since we're not adding any user level data, we should remove this tool tip.

**Comment by gajrajgchouhan** [comment]
Can I pick this up?

**Comment by dhruvagarwal** [comment]
Ofc! Go ahead @gajrajgchouhan! We'll be happy to assist you in this journey.. looking forward to your first PR!
