### ISSUE TITLE
Sorting of pull requests insights is broken

### ISSUE THREAD

**Issue by titpetric** [middlewarehq/middleware#369]
### Description:

Sorting on columns doesn't work as expected.

### Steps to reproduce:

1. go to pull requests insights
2. click sortable columns and verify ascending/descending order isn't there as expected

### Expected behavior:

- I expected the lead time to be sortable and change asc/desc
- I expected subcolumns (lines, comments) to be sortable

### Actual behavior:

- Commits/lines/comments is a single column being sorted
- Lead time sort isn't correct (3d > 2h > 1h > 3d?)...
- Lead time sort doesn't change with asc/desc

![image](https://github.com/middlewarehq/middleware/assets/233360/af2401bd-0189-45a1-863f-e90bffc269c0)

**Comment by jayantbh** [comment]
Oh yeah, lead time sort definitely looks broken, and commits/lines/etc. being grouped doesn't help. We'll fix those. 🚀
