### ISSUE TITLE
Date range picker doesn't activate the apply button

### ISSUE THREAD

**Issue by titpetric** [middlewarehq/middleware#370]
### Description:

The UI component for choosing the date range doesn't activate "apply" on modification of range

### Steps to reproduce:

1. click date range
2. change date range
3. observe the apply button

### Expected behavior:

Expected the date range change from the left side (30d, 90d, etc.) to activate the apply button. The apply button seems to be activated only if a manual range is chosen with the date picker.

### Actual behavior:

![image](https://github.com/middlewarehq/middleware/assets/233360/f093e9ca-158d-4d4f-9104-9558e6fc8486)

**Comment by e-for-eshaan** [comment]
Hey @titpetric ! I have fixed the behaviour, now selecting a date-preset (eg: Last 90d) will select the date-range and close the modal, implying that selection has been made. You can take a pull and tell us how it works!
