### ISSUE TITLE
Sorting by lines doesn't work

### ISSUE THREAD

**Issue by e-for-eshaan** [middlewarehq/middleware#397]
### Description:

Clicking on the `LINES` header on the PR table doesn't sort correctly

### Steps to reproduce:

1. Go to `/dora-metrics`
2. Click lead-time stats card
3. in the PR table beneath, try sorting by number of lines

### Expected behavior:

- should sort perfectly by number of lines

### Actual behavior:

- sort is broken

### Server Setup Information:

- Operating System: 
- Deployment Method:

**Comment by KartikChawla09** [comment]
The `conf.field` is labelled as `additions` but line changes actually is the sum of `additions` and `deletions`. I am working towards fixing this issue.
