### ISSUE TITLE
Sorting by response time

### ISSUE THREAD

**Issue by e-for-eshaan** [middlewarehq/middleware#399]
### Description:

Clicking on the `RESPONSE` header on the PR table doesn't sort correctly

### Steps to reproduce:

1. Go to `/dora-metrics`
2. Click lead-time stats card
3. in the PR table beneath, try sorting by response time, commit to open

### Expected behavior:

- should sort perfectly by response time, commit to open

### Actual behavior:

- sort is broken

### Server Setup Information:

- Operating System: 
- Deployment Method:

**Comment by KartikChawla09** [comment]
I would like to work on this issue. Can someone please assign this to me ?

**Comment by e-for-eshaan** [comment]
@KartikChawla09 turns out this issue was already fixed by me, forgot to close this issue back then!
