### ISSUE TITLE
Wrong Deployments number shown

### ISSUE THREAD

**Issue by gabrielenosso** [middlewarehq/middleware#407]
### Description:
Number of deployments shown is completely wrong.
Also deployments shown are not considering the branch selected.

### Steps to reproduce:
Selected default production branch as "master"
![image](https://github.com/middlewarehq/middleware/assets/4018887/9c3412f0-aac4-4417-a808-22538de5252b)

Deployments shown are considering all branches (it should consider only the "master" branch)
![image](https://github.com/middlewarehq/middleware/assets/4018887/c1d2e650-5277-433c-b701-c3dbbedc1e8e)
So numbers and data here are wrong (first problem).

Second problem:
from the previous screenshot you can see that there are 2 deployments to the master branch.
But the dashboard shows only 1 per week (when you can see that I selected only 3 days...).
Also the tooltip says "2 deployments over 0 weeks 6 days"... number of deployments here is correct, but time is wrong (should be 3 days)
![image](https://github.com/middlewarehq/middleware/assets/4018887/fe8fce83-c6cd-4553-b238-6f2e47c95860)

### Expected behavior:
numbers shown are correct

### Server Setup Information:
just followed the instructions on the readme to start the app

**Comment by shivam-bit** [comment]
Hi @gabrielenosso 
The first issue has been resolved; deployments will now only show insights specific to the selected branch mode. 
You can pull the latest changes and try it out. 

PS- we are still looking into the second issue.

**Comment by amoghjalan** [comment]
Hi @gabrielenosso 
Thank you for bringing this to our attention. We've identified that this issue occurs when the selected date range is less than 7 days. After careful consideration, we believe that metrics for such a short duration don't add much value. Therefore, we are considering setting the minimum date range to 7 days.

We'd love to hear your thoughts on this approach and any feedback you might have.

**Comment by gabrielenosso** [comment]
Makes sense. 1 week is fine as minimum.
Point is all UI should not permit a selection of less than 7 days then (and it should be clear :) )
