### ISSUE TITLE
Private repos not showing in "Add Repositories"

### ISSUE THREAD

**Issue by MaximPiessen** [middlewarehq/middleware#408]
### Description:

When linking my github account, by setting up the PAT as described in the screenshot, I cannot add (personal / organization) private repos when setting up a team. 

### Steps to reproduce:

1. Set up your PAT, link GitHub 
2. Go to Create Team
3. Search for a private repo

### Expected behavior:

Ability to link private repositories.

**Comment by jayantbh** [comment]
Hey @MaximPiessen, apologies for the late response.
Could you try to search for the repo by typing in the name like "orgname/reponame"?

For example, for Middleware I might do "middlewarehq/middleware". Could you check this?

**Comment by MaximPiessen** [comment]
Thanks for your reply. Sadly, it's still not showing up; only public repos do (see screenshots)

<img width="300" alt="Screenshot 2024-06-12 at 10 41 56" src="https://github.com/middlewarehq/middleware/assets/31801298/75fdb794-f462-415a-8172-4fb7956cc6de">
<img width="311" alt="Screenshot 2024-06-12 at 10 42 04" src="https://github.com/middlewarehq/middleware/assets/31801298/d90e5f61-8001-4aa6-a50c-db58e8ae8e7d">

**Comment by MaximPiessen** [comment]
@jayantbh any update on this? Thanks!

**Comment by jayantbh** [comment]
Hey @MaximPiessen! 
Apologies for the delay and thanks for the follow up!

Let me get someone from the team involved to check this out.

**Comment by Kamlesh72** [comment]
I am able to find my public/private repos as well as public/private repos where I am a member or collaborator.

**Comment by Kamlesh72** [comment]
@MaximPiessen Are you there?

**Comment by jayantbh** [comment]
Deepest apologies for the lack of comms on this from our end, @MaximPiessen

Could you follow the troubleshooting steps [here](https://github.com/middlewarehq/middleware?tab=readme-ov-file#%EF%B8%8F-troubleshooting) to update your Middleware image to the latest version and confirm that you're still facing the issue?
