### ISSUE TITLE
Make selectable date range to be minimum 7 days

### ISSUE THREAD

**Issue by samad-yar-khan** [middlewarehq/middleware#424]
## Why do we need this ?

- We need the minimum date range to be 7 days because the data for less than 7 days is not retrospective or actionable.

![image](https://github.com/middlewarehq/middleware/assets/70485812/b4bd8de6-c146-4841-9e28-0d01a6f3f174)

## Acceptance Criteria

- [ ] Make minimum selectable date range to be 7 days

**Comment by Kamlesh72** [comment]
May I work on this issue?

**Comment by samad-yar-khan** [comment]
@jayantbh  Hey can help me navigate which files to look into ?

**Comment by jayantbh** [comment]
Sure! You'll want to look into components/DateRangePicker to start with.

**Comment by samad-yar-khan** [comment]
@jayantbh  can you assign this to me ?

**Comment by jayantbh** [comment]
Done! Go ahead!

**Comment by samad-yar-khan** [comment]
@jayantbh  hey can you look into #428 as it solves this issue

**Comment by jayantbh** [comment]
Got it! The PR looks good! Approved.
We can go ahead.
