### ISSUE TITLE
Postgres and Redis Log streams are Interchanged

### ISSUE THREAD

**Issue by Kamlesh72** [middlewarehq/middleware#471]
### Description:

On selecting Postgres as LogSource, the logs of Redis are shown and vice versa.

### Steps to reproduce:

1. `./dev.sh`
2. Once the container is ready, Press "e", Here Postgres logs are shown.
3. Press "r", Now Redis logs are shown.

### Expected behavior:

The Postgres logs should be displayed by selecting Postgres as log source and vice versa.

### Actual behavior:

![Screenshot 2024-07-10 at 12 18 32 PM](https://github.com/middlewarehq/middleware/assets/90441742/b958bd4e-c040-4e94-a6a5-4904fae5795e)

**Comment by Kamlesh72** [comment]
@jayantbh May I create a PR for this?

**Comment by jayantbh** [comment]
Sure, @Kamlesh72
