### ISSUE TITLE
Add docker version details on the sidebar

### ISSUE THREAD

**Issue by amoghjalan** [middlewarehq/middleware#478]
## Why do we need this ?
Currently, the Docker version details are only visible during the initial application setup. After initialization, this information is not accessible. To ensure better visibility and management, we need a persistent location where the current Docker version in use is displayed. This will also allow us to include a call-to-action (CTA) for updating the version if it becomes outdated.

## Acceptance Criteria

- [ ] Display the current Docker version prominently within the application interface.
- [ ] Ensure the Docker version information is updated in real-time or at regular intervals.
- [ ] Include a CTA button or link that guides users to update their Docker version if an update is available.

**Comment by samad-yar-khan** [comment]
@amoghjalan  How should I mitigate this ?

**Comment by Kamlesh72** [comment]
@amoghjalan is this about our docker image or docker software version ?

**Comment by jayantbh** [comment]
I think I'll close this. This issue was created for demo purposes earlier. Showing the version of the docker CLI in-app doesn't offer much value.
