### ISSUE TITLE
Team Repos Removed from list on backspace

### ISSUE THREAD

**Issue by samad-yar-khan** [middlewarehq/middleware#510]
### Description:

Whenever I try to do a backspace on repo search bar, the pre selected  team repos get removed from the list.

### Steps to reproduce:

1. Go to manage teams.
2. Search repos
3. Select Repos
4. Click backspace on the repo search bar.
5. Repos will get removed from the list. 

https://github.com/user-attachments/assets/783da228-f3b2-42a6-a914-079f1bcd988a

### Expected behavior:

- Existing team repo mappings should not get deleted.

### Actual behavior:

- Existing Repos get deleted from the team repos list.

### Server Setup Information:

- Operating System: 
- Deployment Method:

**Comment by VipinDevelops** [comment]
Hey @samad-yar-khan I would like to work on this issue

**Comment by samad-yar-khan** [comment]
Sure, give it a go.

**Comment by jayantbh** [comment]
Thanks to @VipinDevelops, this is now closed.
