### ISSUE TITLE
Remove unused setting `should_sync_alerts_as_incidents`

### ISSUE THREAD

**Issue by samad-yar-khan** [middlewarehq/middleware#521]
## Why do we need this ?

- We currently have usages of a setting with key `should_sync_alerts_as_incidents`  in the bff. This API is not being used in the BFF and the setting type is not in the backend anymore. 
- Unused code and tech debt

## Acceptance Criteria

- [ ] Remove any usages and api calls for the setting with key  `should_sync_alerts_as_incidents`

**Comment by VipinDevelops** [comment]
Hey @samad-yar-khan 
Can you assign this to me

I would like to explore our backend.
And remove unused code.

**Comment by jayantbh** [comment]
Hey @VipinDevelops, apologies for the delay on this one, but yes, you can take this up. :)

**Comment by Kamlesh72** [comment]
Can I work on this? @jayantbh

**Comment by jayantbh** [comment]
Sure @Kamlesh72. I'll assign this to you.

**Comment by VipinDevelops** [comment]
Hey @Kamlesh72  Yeah you can work on this
