### ISSUE TITLE
Allow Caps-locked keys on CLI

### ISSUE THREAD

**Issue by e-for-eshaan** [middlewarehq/middleware#525]
### Description:

Currently, is a capslock is selected, the CLI fails to work. This shouldn't be the case.

### Steps to reproduce:

1. Run `./dev.sh`
2. Press caps-lock
3. try to exit the CLI by pressing `x`

### Expected behavior:

CLI should exit

### Actual behavior:

Does nothing, just jitters

**Comment by Kamlesh72** [comment]
Does this needs to be handled for other keys also? Like q, w, e, a etc.

**Comment by jayantbh** [comment]
I think that should be case across all other keys.

**Comment by nisalikularatne** [comment]
Hi there @e-for-eshaan could you assign this ticket to me?

**Comment by e-for-eshaan** [comment]
Sure @nisalikularatne !

**Comment by nisalikularatne** [comment]
@e-for-eshaan https://github.com/middlewarehq/middleware/pull/526 this is the PR for the above issue. Let me know if you have any concerns!
