### ISSUE TITLE
Add a create teams CTA right onto the teams-selector

### ISSUE THREAD

**Issue by e-for-eshaan** [middlewarehq/middleware#529]
## Why do we need this ?

- We can have a `+ add team` CTA button right onto the team-selector, right under here.

<img width="415" alt="image" src="https://github.com/user-attachments/assets/bb6e1fc8-470b-4f5a-a1e0-6934b766f59a">

**Comment by VipinDevelops** [comment]
Hey @e-for-eshaan seems like a fairly simple thing to do I want to it a shot, we just want to a button that handle creating a new team similar to how we create a team right ?

**Comment by VipinDevelops** [comment]
Right now we use this page to create new Team 
![image](https://github.com/user-attachments/assets/623a20df-57f6-4e2b-8ecf-cd15730351be)
do you want this inside the small modal you shared ?

**Comment by VipinDevelops** [comment]
I think we should move the create Team option in an overlay for this 
![image](https://github.com/user-attachments/assets/35b57926-dfa5-4b7e-b79f-a7bcb88c837f)

**Comment by e-for-eshaan** [comment]
How about this.
- a url that open the teams page with creation form being already opened.
- `http://localhost:3333/teams?create=true`


on redirecting to this url, 
- a useEffect consumes the query, 
- opens the create-form, 
- and removes the query from the url, setting it back to `http://localhost:3333/teams`

[completely optional]: might as well handle [this](https://github.com/middlewarehq/middleware/issues/537)

**Comment by VipinDevelops** [comment]
Let me share @e-for-eshaan 

what I understood by clicking the button is that we will redirect to the team page but with a query we can use that query to open the team's modal and we can remove the query once we opened the modal in the teams page 

Is that what you mean ?

**Comment by VipinDevelops** [comment]
Let me share @e-for-eshaan 

what I understood by clicking the button is that we will redirect to the team page but with a query we can use that query to open the team's modal and we can remove the query once we opened the modal in the teams page 

Is that what you mean ?


Can you explain this one in more detail ?https://github.com/middlewarehq/middleware/issues/537
