### ISSUE TITLE
Auto select team that was just created

### ISSUE THREAD

**Issue by e-for-eshaan** [middlewarehq/middleware#537]
## Why do we need this ?

on team creation success, select the team. don't update selection for editing/updating team though

**Comment by VipinDevelops** [comment]
Hey @e-for-eshaan 
Can you explain to me a little what is the expected behaviour and how you suggest this to be built.

**Comment by e-for-eshaan** [comment]
the moment someone creates a team
- use `.then` on a dispatch
- check if it was successful
- select the team just created by updated the `singleTeam` in app-slice

**Comment by VipinDevelops** [comment]
Understood
