### ISSUE TITLE
Add CodeQL Security Analysis Workflow

### ISSUE THREAD

**Issue by sagnik3788** [middlewarehq/middleware#543]
## Why do we need this ?
Implement a CodeQL workflow to perform security analysis on the codebase. This will help in identifying potential vulnerabilities and improving the overall security posture of the project.

**Comment by jayantbh** [comment]
Hey @sagnik3788, what is the average runtime of a codeql workflow?

**Comment by sagnik3788** [comment]
@jayantbh, approx 15-30 minutes. Do we need this?

**Comment by jayantbh** [comment]
I think not for now then. The Github Security tab could use more attention as it already is. :D
