### ISSUE TITLE
AI Analysis 500 Error

### ISSUE THREAD

**Issue by dvngnt** [middlewarehq/middleware#546]
### Description:

http://localhost:3333/api/internal/ai/dora_metrics 500 (Internal Server Error)

### Steps to reproduce:

1. Generate open api key
2. Enter key in middleware

### Expected behavior:
AI reports

### Actual behavior:
![image](https://github.com/user-attachments/assets/4b6a5308-25f0-43f4-9402-4e1e8cfe3c89)

**Comment by jayantbh** [comment]
Hey @dvngnt, thanks for reporting the issue! :)

Could you confirm that there's no accidental whitespaces or something else possibly wrong with the token?

---
In any case, it appears that the error message should have been better than... that.

**Comment by dvngnt** [comment]
@jayantbh i'm copying directly from https://platform.openai.com/api-keys

Permissions
Read and write API resources

**Comment by jayantbh** [comment]
Yeah that seems like it should definitely work.
We'll look into this, though any help is absolutely appreciated. :)

**Comment by jayantbh** [comment]
Just as another quick check:
Could you confirm that your OpenAI billing/credits/usage limits are not a factor?

Additionally:
Any logs from the CLI, or the system status UI while you run into this error could help us further. :)
In case you're unable to get logs from the above means, or need a greater amount of logs, you can access the relevant files by means of `docker exec -it ...` directly. Instructions here: https://github.com/middlewarehq/middleware#:~:text=port%3A%206385.-,View%20the%20logs,-%3A%20Although%20the%20CLI

**Comment by Kamlesh72** [comment]
@jayantbh Chatgpt doesn't have free plan right?

**Comment by dvngnt** [comment]
Not for their API. I believe that's per request

**Comment by VipinDevelops** [comment]
I will look into It Give me some time I will update you ASAP

**Comment by VipinDevelops** [comment]
Hey  @dvngnt  I tried to reproduce the issue you are facing and  it's working fine for me using open AI 
![image](https://github.com/user-attachments/assets/26eb585c-1cde-42bc-9552-132dfd18f4d4)

**Comment by dvngnt** [comment]
Thanks for the responses. I'll try to attempt again later today.

**Comment by Kamlesh72** [comment]
@VipinDevelops you added min. $5 credits for chatgpt api right?

**Comment by dvngnt** [comment]
I think that might be the problem. the key is created but more of a
credits/billing issue. I don't believe middleware is the issue.

Thank you

**Comment by VipinDevelops** [comment]
Thanks @dvngnt 
Don't close is I am thinking of adding a check for error so at least we get some better error than 500 if something goes wrong.

**Comment by jayantbh** [comment]
I believe this has been handled for now. Closing. :)
