### ISSUE TITLE
Auto-Scroll for Logs

### ISSUE THREAD

**Issue by VipinDevelops** [middlewarehq/middleware#574]
## Why do we need this ?
Auto-scrolling in logs will enhance convenience for users.

![image](https://github.com/user-attachments/assets/0a5c7ba9-51da-4303-95c7-5ade5c3ed235)

## Acceptance Criteria
- [ ]  Implement logic to automatically scroll to the bottom of the logs file.

**Comment by xyfer17** [comment]
@VipinDevelops I would like to work on this enhancement as it's pretty straight forward. Could you please assign it to me?

**Comment by VipinDevelops** [comment]
Go Ahead @xyfer17

**Comment by xyfer17** [comment]
@VipinDevelops just take a look on [PR](https://github.com/middlewarehq/middleware/pull/581) and let me know will i have to change anything else.
