### ISSUE TITLE
Dev build is failing

### ISSUE THREAD

**Issue by vishalmishraa** [middlewarehq/middleware#579]
### Steps to reproduce:

1.  run `./dev.sh`
2. 
3. 

### Actual behavior: fail to run 

![Screenshot 2024-10-08 at 2 24 19 AM](https://github.com/user-attachments/assets/01fca3f7-002d-41b8-bf0f-c1c15adeddf9)

### Server Setup Information:

- Operating System: debian 12
- Deployment Method:  

### Additional context

In `./web-server/package.json` , engine version should be latest to 22.9.0  (or as decided by the team) . also update readme .

**Comment by jayantbh** [comment]
Hey @vishalmishraa, a related PR is active for this:
https://github.com/middlewarehq/middleware/pull/554

For now, you may be able to remove the engines field (and not commit the change) to continue on it perhaps?

**Comment by adnanhashmi09** [comment]
Please take the pull of the main branch and try again. Should work now @vishalmishraa
