### ISSUE TITLE
Fix All-File Linting CI Check

### ISSUE THREAD

**Issue by jayantbh** [middlewarehq/middleware#599]
### Description:

https://github.com/middlewarehq/middleware/actions/runs/11361444183/job/31601170327?pr=596

This check has been failing for every PR for reasons unrelated to the PR itself.

**Comment by mokshith-moksh** [comment]
I have fixed this issue , can I raise the PR 
![Screenshot 2024-10-18 at 11 31 11 AM](https://github.com/user-attachments/assets/6836760b-1ab8-47d0-84c9-a2ee78188a67)
