### ISSUE TITLE
Fix linting for local development

### ISSUE THREAD

**Issue by jayantbh** [middlewarehq/middleware#600]
### Description:

The linter doesn't seem to work correctly on respective codebases and often breaks the linting check wasting dev time.

- The linter should work locally on respective submodules locally.
- The linter should work on saving of files (it should run on as few files [only the currently changed file(s) ideally] as possible).
- It should work on respective files regardless of whether I opened the submodule directly, or the whole repo.
- It should work at least in VSCode perfectly. But support in other IDEs is great too, but the main goal is to get it working in VSC.

**Comment by mokshith-moksh** [comment]
Hi @jayantbh ,

I would like to work on this issue (#600) and would appreciate it if you could assign it to me. I'm eager to contribute and resolve this.

Thank you!

**Comment by jayantbh** [comment]
Hey @mokshith-moksh, sure feel free to give it a shot.
However, I'm leaving it unassigned till you're able to share a PR. All the best!

**Comment by mokshith-moksh** [comment]
I am considering adding the linter to the backend, as currently only the cli and web-server directories have it configured. My approach to solving this would be to add Husky and Lint-Staged, and optimize the .vscode/settings.json, ESLint, and Prettier configuration files. Is this approach correct, and should I proceed with it?

**Comment by mokshith-moksh** [comment]
Hi @jayantbh 
I have implemented it , can you help in testing it

**Comment by jayantbh** [comment]
Sure. It'll help you could share a screen recording of it in action.

**Comment by mokshith-moksh** [comment]
Hi @jayantbh , 

I have resolved the issue. To pass the test related to ESLint in the Next.js project, I needed to install the dependencies listed in the pre-commit.yml file. This ensures that the code passes the linting checks. However, the cli and web-server were missing some of the dev dependencies that were required for the tests. I have configured the .vscode/settings.json file for both, and also added the .vscode/settings.json folder at the root level, which helps with linting. I tested this setup, and it is working well. in this below test linter is automatically converting double quotes to single quotes . Can I proceed with raising the PR? 

https://github.com/user-attachments/assets/937e1121-a7df-4d52-bb65-b5f65e9e6330

Thank you!

**Comment by jayantbh** [comment]
Sure you can raise the PR.
I'm wondering however that I think the default quotes behaviour was to use double quotes for strings.

I might be wrong but could you confirm just in case?
Basically there shouldn't be different or conflicting linting configurations in the repo.

**Comment by mokshith-moksh** [comment]
Hi @jayantbh,

Previously, the single or double quotes behavior was not specified in the ESLint configuration file. Now, I have implemented the use of single quotes since most of the repository follows this convention. I have configured both the cli and web-server projects to have the same behavior, ensuring consistent linting across the entire repository.

Thank you!
