### ISSUE TITLE
Upgrade Dependency: Axios from 0.28.1 to 1.7.4

### ISSUE THREAD

**Issue by jayantbh** [middlewarehq/middleware#601]
## Why do we need this ?

This thing is an issue on it's own because axios introduces several breaking changes that require some investigating and debugging to ensure the app doesn't break.

Anyone is free to take this up.

This will fix several dependabot security alerts.
https://github.com/middlewarehq/middleware/security/dependabot

**Comment by Reterics** [comment]
Hi @jayantbh 

I am happy to check this along with the NextJS update. Is it possible for me to work on them?

**Comment by jayantbh** [comment]
Hey @Reterics, sure, I'd be happy to assign this to you, but let's take those on as separate efforts and tackle them one at a time. :)
