### ISSUE TITLE
Failed to run the task

### ISSUE THREAD

**Issue by Raks-simple** [middlewarehq/middleware#615]
### Description:

I am creating rules to get my Facebook forms in Vtiger

### Steps to reproduce:

1. When I click on any option to avoid duplicate registrations, I get a notice telling me to fill out mandatory fields.
2. If I don't select any restrictions to avoid duplicates, it lets me save the rule.
3. Once the rule is saved, I click on Rule de rule and I get the error "Failed to run the task".
4. I have already reviewed all the fields and I don't see any errors.
5. I checked the hidden fields in the system to see if any of them were required at the time but none of them are or were required.
6. I couldn't find the fault.

### Expected behavior:

That can run the rule and get the records in the Vtiger Contacts module. I hope you can tell me what could be happening and how to fix it. I hadn't had a problem with other accounts.

### Actual behavior:

I get the error "Failed to run the task"

![image](https://github.com/user-attachments/assets/0abacd7e-b526-4f4e-bf8a-deca7fba432a)

### Server Setup Information:

Myddleware v2.5.5
Vtiger 7.4

### Additional context

Attach images

1. When I click on any option to avoid duplicate registrations, I get a notice telling me to fill out mandatory fields.

![image](https://github.com/user-attachments/assets/4bd14bfe-8782-4955-ac7a-25ad064af7ca)

2. If I don't select any restrictions to avoid duplicates, it lets me save the rule.

![image](https://github.com/user-attachments/assets/6e168019-3895-4416-a4c3-014ba39b6d60)

3. Correct simulation

![image](https://github.com/user-attachments/assets/9f4eb3d7-7054-41dd-8072-7cb11c76b5fb)

**Comment by jayantbh** [comment]
Hey @Raks-simple, you might be looking for this one:
https://github.com/Myddleware/myddleware
