### ISSUE TITLE
[github]Not all git repos are seen in the org

### ISSUE THREAD

**Issue by sokoow** [middlewarehq/middleware#617]
### Description:

Hi All, I have an organization plugged into middleware through github through a PAT token. While most of my repos are being seen by middleware, some repos are not seen by it. This is true for repos that have same permissions set, some are being picked up by middleware, some are not. What would be the correct way of logging/troubleshooting this?

### Steps to reproduce:

1. Start typing org name and repo name org/repo
2. Observe 'not found' being displayed, despite that the repo is there

### Expected behavior:

I'd expect for all my org repos to be picked up by middleware

### Actual behavior:

![image](https://github.com/user-attachments/assets/1caf8fc4-a916-44c1-a544-9a77e52731e6)

### Server Setup Information:

I'm running an opensource dev docker-compose of middleware, with default vars.

**Comment by jayantbh** [comment]
Hey @sokoow, thanks for reaching out. :)

Could you try pasting the link of the repo in the input field?

Additionally, in your specific screenshot, I notice that you've added:
idependenc3/fe-monorepo

I'm assuming `idependenc3` is the name of the intended GH org.

However, I suspect it might just be a typo, since I found an organization by this name instead:
https://github.com/independenc3

Could you confirm whether it's not a typo, and share a link to the correct org?

**Comment by jayantbh** [comment]
Does the repo show up if you correct the typo?
If it doesn’t show up anyway, could you share the response of this API:

https://api.github.com/repos/middlewarehq/middleware
Of course, you’ll need to replace the org and repo name as:
https://api.github.com/repos/{org or user name}/{repo name}

Could you also confirm that pasting the link to the repo in the input field doesn’t work either?

**Comment by sokoow** [comment]
I can confirm that pasing repo link to the dialog box does nothing, just tested it. I'll get you the api response in a moment.

**Comment by sokoow** [comment]
Ah, I see a pattern here, both of my repos that middleware doesn't see are.. forks. Is there any special way to specify forked repos?

**Comment by sokoow** [comment]
strange, all repos is questions seem to be returning: 
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/repos/repos#get-a-repository",
  "status": "404"
}```
and they are there, what is wrong with this thing ? :)

**Comment by jayantbh** [comment]
Very interesting. I would expect forks to show up like regular repos.

But if GitHub APIs don't see the repo, makes sense why Middleware isn't able to see it either.

We'll check with other forks on our end if this is some kind of an edge case.

Meanwhile, any info you could share about the behaviour of GH APIs with forks would help us greatly.

If you could also share the exact API you tried to hit, that'll help as well.

**Comment by jayantbh** [comment]
@sokoow I'm not sure if it's necessarily related to forks.
https://api.github.com/repos/jayantbh/good-first-issue

This is a repo that I'd forked earlier, and I get the response on it just fine.
**Could you share the API that you tried to hit?**

You could also join our Slack community and we could get on a quick huddle to sort this out.

**Comment by jayantbh** [comment]
Here you go: https://mhq.link/oss-community
I'll be a bit occupied tomorrow, but later in the day (local time) I'll be around. Feel free to ping me (Jayant) and I'll let you know when I'm around.

**Comment by jayantbh** [comment]
This issue was resolved a couple weeks ago I think. :)
